{% set name = "certbot" %}
{% set version = "1.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-{{ version }}.tar.gz
  sha256: 9ab71e7d85e4b3cbce7fa5dc067ee932866e346e9034438d4d5aa34ff98ebff8

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - certbot = certbot.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - acme >={{ version }}
    - configargparse >=0.9.3
    - configobj >=5.0.6
    - cryptography >=2.5.0
    - distro >=1.0.1
    - josepy >=1.9.0
    - parsedatetime >=2.4
    - pyrfc3339
    - python
    - pytz
    - pywin32 >=300  # [win]
    - setuptools >=39.0.1
    - zope.component
    - zope.interface

test:
  imports:
    - certbot
    - certbot._internal
  commands:
    - pip check
    - certbot --help
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME client
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
